# Generated by Django 4.2.7 on 2025-08-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url_path", models.CharField(max_length=255, unique=True)),
                (
                    "authentication_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("secret", "Secret Token"),
                            ("signature", "HMAC Signature"),
                            ("basic", "Basic Auth"),
                            ("bearer", "Bearer Token"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("secret_token", models.CharField(blank=True, max_length=255)),
                (
                    "signature_header",
                    models.CharField(default="X-Hub-Signature-256", max_length=100),
                ),
                ("allowed_methods", models.JSONField(default=list)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("custom_headers", models.JSONField(blank=True, default=dict)),
                ("rate_limit_requests", models.IntegerField(default=100)),
                ("rate_limit_window", models.IntegerField(default=3600)),
                ("timeout_seconds", models.IntegerField(default=30)),
                ("retry_attempts", models.IntegerField(default=3)),
                ("retry_delay", models.IntegerField(default=60)),
                (
                    "data_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("form", "Form Data"),
                            ("xml", "XML"),
                            ("raw", "Raw"),
                        ],
                        default="json",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="organizations.organization",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_endpoints",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_id", models.CharField(max_length=255, unique=True)),
                ("trigger_event", models.CharField(max_length=100)),
                ("request_method", models.CharField(default="POST", max_length=10)),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.TextField()),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("max_attempts", models.IntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
            },
        ),
        migrations.CreateModel(
            name="WebhookTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("teams", "Microsoft Teams"),
                            ("generic", "Generic HTTP"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("default_config", models.JSONField(default=dict)),
                ("example_payload", models.JSONField(default=dict)),
                ("setup_instructions", models.TextField(blank=True)),
                ("validation_rules", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webhook_templates",
                "indexes": [
                    models.Index(
                        fields=["webhook_type", "is_active"],
                        name="webhook_tem_webhook_498800_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="webhook_tem_created_31d0fc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("request_count", models.IntegerField(default=0)),
                (
                    "window_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_rate_limits",
                "indexes": [
                    models.Index(
                        fields=["webhook_endpoint", "ip_address"],
                        name="webhook_rat_webhook_99b6e2_idx",
                    ),
                    models.Index(
                        fields=["window_start"], name="webhook_rat_window__8e0bf7_idx"
                    ),
                ],
                "unique_together": {("webhook_endpoint", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workflow_start", "Workflow Started"),
                            ("workflow_complete", "Workflow Completed"),
                            ("workflow_failed", "Workflow Failed"),
                            ("node_execute", "Node Executed"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_data", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                ("processing_result", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_events",
                "indexes": [
                    models.Index(
                        fields=["webhook_endpoint", "event_type"],
                        name="webhook_eve_webhook_9355d0_idx",
                    ),
                    models.Index(
                        fields=["processed", "created_at"],
                        name="webhook_eve_process_8c85e6_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="webhook_eve_event_t_54b761_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["organization", "status"], name="webhook_end_organiz_1c3321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["url_path"], name="webhook_end_url_pat_5365dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["workflow"], name="webhook_end_workflo_7ced8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook_endpoint", "status"],
                name="webhook_del_webhook_be1b64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["delivery_id"], name="webhook_del_deliver_399fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_retry_at"], name="webhook_del_status_741062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["created_at"], name="webhook_del_created_50111d_idx"
            ),
        ),
    ]
